---
host_ip: "62.84.119.10"

clickhouse_version: "22.4.6.53"
clickhouse_packages:
  - clickhouse-client
  - clickhouse-server
  - clickhouse-common-static

vector_version: "0.21.1"
vector_os_arch: "x86_64"
vector_workdir: "/home/ubuntu/vector"
vector_os_user: "vector"
vector_os_group: "vector"